[package]
name = "adder"
version = "0.1.0"
edition = "2021"

[dependencies]
# Cargo doesn’t assume that crates in a workspace will depend on each other, so we need to be explicit about the dependency relationships.
add_one = { path = "../add_one" }
rand = "0.8.5"
